name: Build Docker image
on:
  push:
    branches-ignore:
      - dc4eu-rome
      - master
  pull_request:

jobs:
  push-ehic:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit
    with:
      image-tag: ghcr.io/gunet/wallet-enterprise-ehic-issuer:latest
      docker-push: true
      dockerfile-path: ./wallet-enterprise-configurations/ehic-issuer/Dockerfile
