name: Build Docker image
on:
  push:
    branches-ignore:
      - master
      - dc4eu-rome
  pull_request:

jobs:
  build-vid:
    permissions:
      contents: read
      packages: read

    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit
    with:
      image-tag: ghcr.io/gunet/wallet-enterprise-vid-issuer:latest
      docker-push: false
      dockerfile-path: ./wallet-enterprise-configurations/vid-issuer/Dockerfile
