name: Build Docker image
on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build-acme:
    permissions:
      contents: read
      packages: read

    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit
    with:
      image-tag: ghcr.io/wwwallet/wallet-enterprise-acme-verifier:latest
      docker-push: false
      dockerfile-path: ./wallet-enterprise-configurations/acme-verifier/Dockerfile
