name: Build Docker image
on:
  push:
    branches-ignore:
      - dc4eu-rome
      - master
  pull_request:

jobs:
  build-ehic:
    permissions:
      contents: read
      packages: read

    uses: ./.github/workflows/docker-build-push.yml
    # secrets:
    #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      image-tag: ghcr.io/gunet/wallet-enterprise-ehic-issuer:latest
      docker-push: false
      dockerfile-path: ./wallet-enterprise-configurations/ehic-issuer/Dockerfile
