name: Push Docker image
on:
  push:
    branches:
      - dc4eu-rome

jobs:
  push-vid:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit
    with:
      image-tag: ghcr.io/gunet/wallet-enterprise-vid-issuer:latest
      docker-push: true
      dockerfile-path: ./wallet-enterprise-configurations/vid-issuer/Dockerfile
