name: Push Docker image
on:
  push:
    branches:
      - dc4eu-rome

jobs:
  push-pda1:
    permissions:
      contents: read
      packages: write

    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit
    with:
      image-tag: ghcr.io/gunet/wallet-enterprise-pda1-issuer:latest
      docker-push: true
      dockerfile-path: ./wallet-enterprise-configurations/pda1-issuer/Dockerfile
